### ISSUE TITLE
Node-RED package installaion problem

### ISSUE THREAD

**Issue by sztof** [gausma/nodered-contrib-signal-client#5]
I have a problem with installation of this package on the Node-RED,
Could you have a look what is going on here?

-----------------------------------------------------------
2021-01-14T08:44:24.689Z Install : nodered-contrib-signal-client 2.0.1

2021-01-14T08:44:24.892Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production nodered-contrib-signal-client@2.0.1
2021-01-14T08:45:20.151Z [out] 
2021-01-14T08:45:20.151Z [out] > fs-ext@0.5.0 install /config/node-red/node_modules/fs-ext
2021-01-14T08:45:20.151Z [out] > node-gyp configure build
2021-01-14T08:45:20.151Z [out] 
2021-01-14T08:45:22.891Z [err] gyp
2021-01-14T08:45:22.891Z [err]  
2021-01-14T08:45:22.892Z [err] ERR! build error 
2021-01-14T08:45:22.893Z [err] gyp
2021-01-14T08:45:22.894Z [err]  ERR! 
2021-01-14T08:45:22.894Z [err] stack Error: not found: make
2021-01-14T08:45:22.894Z [err] gyp ERR! stack
2021-01-14T08:45:22.895Z [err]      at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2021-01-14T08:45:22.895Z [err] gyp ERR!
2021-01-14T08:45:22.895Z [err]  stack
2021-01-14T08:45:22.895Z [err]      at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2021-01-14T08:45:22.895Z [err] gyp ERR! stack
2021-01-14T08:45:22.895Z [err]      at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2021-01-14T08:45:22.895Z [err] gyp ERR! 
2021-01-14T08:45:22.896Z [err] stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2021-01-14T08:45:22.896Z [err] gyp ERR! 
2021-01-14T08:45:22.896Z [err] stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2021-01-14T08:45:22.896Z [err] gyp ERR! stack
2021-01-14T08:45:22.897Z [err]      at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2021-01-14T08:45:22.897Z [err] gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:168:21)
2021-01-14T08:45:22.897Z [err] gyp
2021-01-14T08:45:22.898Z [err]  ERR! System Linux 4.15.0-123-generic
2021-01-14T08:45:22.898Z [err] gyp ERR! command
2021-01-14T08:45:22.898Z [err]  "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
2021-01-14T08:45:22.898Z [err] gyp 
2021-01-14T08:45:22.898Z [err] ERR! cwd /config/node-red/node_modules/fs-ext
2021-01-14T08:45:22.898Z [err] gyp 
2021-01-14T08:45:22.898Z [err] ERR! node -v
2021-01-14T08:45:22.899Z [err]  v12.18.4
2021-01-14T08:45:22.899Z [err] gyp
2021-01-14T08:45:22.899Z [err]  ERR! node-gyp -v v5.1.0
2021-01-14T08:45:22.899Z [err] gyp ERR! 
2021-01-14T08:45:22.899Z [err] not ok 
2021-01-14T08:45:22.953Z [out] 
2021-01-14T08:45:22.953Z [out] > bufferutil@4.0.3 install /config/node-red/node_modules/bufferutil
2021-01-14T08:45:22.953Z [out] > node-gyp-build
2021-01-14T08:45:22.953Z [out] 
2021-01-14T08:45:23.617Z [out] 
2021-01-14T08:45:23.617Z [out] > utf-8-validate@5.0.4 install /config/node-red/node_modules/utf-8-validate
2021-01-14T08:45:23.617Z [out] > node-gyp-build
2021-01-14T08:45:23.617Z [out] 
2021-01-14T08:45:24.261Z [out] 
2021-01-14T08:45:24.261Z [out] > node-webcrypto-ossl@1.0.49 install /config/node-red/node_modules/node-webcrypto-ossl
2021-01-14T08:45:24.261Z [out] > node-gyp rebuild
2021-01-14T08:45:24.261Z [out] 
2021-01-14T08:45:27.308Z [err] gyp
2021-01-14T08:45:27.309Z [err]  
2021-01-14T08:45:27.309Z [err] ERR! 
2021-01-14T08:45:27.309Z [err] build error 
2021-01-14T08:45:27.311Z [err] gyp
2021-01-14T08:45:27.313Z [err]  ERR! stack Error: not found: make
2021-01-14T08:45:27.313Z [err] gyp ERR! stack
2021-01-14T08:45:27.316Z [err]      at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2021-01-14T08:45:27.316Z [err] gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2021-01-14T08:45:27.316Z [err] gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2021-01-14T08:45:27.316Z [err] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2021-01-14T08:45:27.316Z [err] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2021-01-14T08:45:27.316Z [err] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2021-01-14T08:45:27.316Z [err] gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:168:21)
2021-01-14T08:45:27.316Z [err] gyp
2021-01-14T08:45:27.316Z [err]  ERR! System Linux 4.15.0-123-generic
2021-01-14T08:45:27.317Z [err] gyp
2021-01-14T08:45:27.317Z [err]  ERR! command
2021-01-14T08:45:27.317Z [err]  "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2021-01-14T08:45:27.317Z [err] gyp
2021-01-14T08:45:27.317Z [err]  ERR! 
2021-01-14T08:45:27.317Z [err] cwd /config/node-red/node_modules/node-webcrypto-ossl
2021-01-14T08:45:27.317Z [err] gyp
2021-01-14T08:45:27.317Z [err]  ERR! 
2021-01-14T08:45:27.318Z [err] node -v v12.18.4
2021-01-14T08:45:27.318Z [err] gyp ERR!
2021-01-14T08:45:27.318Z [err]  node-gyp -v v5.1.0
2021-01-14T08:45:27.318Z [err] gyp ERR!
2021-01-14T08:45:27.318Z [err]  not ok 
2021-01-14T08:45:30.761Z [err] npm
2021-01-14T08:45:30.761Z [err]  WARN optional SKIPPING OPTIONAL DEPENDENCY: fs-ext@0.5.0 (node_modules/fs-ext):
2021-01-14T08:45:30.761Z [err] npm WARN optional
2021-01-14T08:45:30.761Z [err]  SKIPPING OPTIONAL DEPENDENCY: fs-ext@0.5.0 install: `node-gyp configure build`
2021-01-14T08:45:30.761Z [err] npm WARN 
2021-01-14T08:45:30.761Z [err] optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
2021-01-14T08:45:30.763Z [err] 
2021-01-14T08:45:30.794Z [err] npm
2021-01-14T08:45:30.795Z [err]  ERR! code ELIFECYCLE
2021-01-14T08:45:30.795Z [err] npm 
2021-01-14T08:45:30.795Z [err] ERR! errno 1
2021-01-14T08:45:30.806Z [err] npm 
2021-01-14T08:45:30.807Z [err] ERR! node-webcrypto-ossl@1.0.49 install: `node-gyp rebuild`
2021-01-14T08:45:30.807Z [err] npm ERR! Exit status 1
2021-01-14T08:45:30.807Z [err] npm 
2021-01-14T08:45:30.807Z [err] ERR! 
2021-01-14T08:45:30.807Z [err] npm ERR!
2021-01-14T08:45:30.807Z [err]  Failed at the node-webcrypto-ossl@1.0.49 install script.
2021-01-14T08:45:30.807Z [err] npm ERR!
2021-01-14T08:45:30.807Z [err]  This is probably not a problem with npm. There is likely additional logging output above.
2021-01-14T08:45:30.878Z [err] 
2021-01-14T08:45:30.878Z [err] npm ERR! A complete log of this run can be found in:
2021-01-14T08:45:30.878Z [err] npm ERR!     /root/.npm/_logs/2021-01-14T08_45_30_859Z-debug.log
2021-01-14T08:45:30.919Z rc=1

**Comment by gausma** [comment]
Seems there is no compiler installed on your system.
I did my tests on a windows system and on a Raspberry Pi OS.
On which operating system and in which environment are you running Node-RED?

**Comment by sztof** [comment]
I am using HomeAssistant Supervised with Node-Redv7.2.11 as addon.
You are right, I had to install manually "alpine-sdk" package, then it works.
I wonder why it was missing, but that is not the case. Thank you for support!

**Comment by baldfox** [comment]
> I am using HomeAssistant Supervised with Node-Redv7.2.11 as addon.
> You are right, I had to install manually "alpine-sdk" package, then it works.
> I wonder why it was missing, but that is not the case. Thank you for support!

Sorry to bring up a closed thread, but could you point me in the direction on how you solved this? Where did you install alpine-sdk? I too am unable to install the node for the same reasons above (hassio (home-assistant supervised) on an intel nuc).

**Comment by sztof** [comment]
> 
> 
> > I am using HomeAssistant Supervised with Node-Redv7.2.11 as addon.
> > You are right, I had to install manually "alpine-sdk" package, then it works.
> > I wonder why it was missing, but that is not the case. Thank you for support!
> 
> Sorry to bring up a closed thread, but could you point me in the direction on how you solved this? Where did you install alpine-sdk? I too am unable to install the node for the same reasons above (hassio (home-assistant supervised) on an intel nuc).

If you are using Home Assistant supervised then you should install porainer addon. It will give you full access for all of your docker images. When you install it, in the container list you can find the node-red addon. Somehing like "addon_a0d7b954_nodered".
Use "console" option as "root" and there you go.

"apk add gcc
apt add g++
apt add build-essential"

That solved my issue

**Comment by baldfox** [comment]
@sztof Thanks for this. I already run portainer (but admittedly have no idea how to run it! All I see is the following. I do have an image with node-red but it doesn't have the console option and says it's unused: 
![image](https://user-images.githubusercontent.com/32448665/106098105-ad78da80-6162-11eb-897a-f0f2c8a13115.png)

**Comment by baldfox** [comment]
I saw your original post and did think to try this prior to your message but it didn't solve the issue, now am wondering if I should reverse what I've done! Any thoughts? 
![image](https://user-images.githubusercontent.com/32448665/106098450-40197980-6163-11eb-810f-bec12e72a7da.png)

**Comment by baldfox** [comment]
@sztof Did you have any specific settings in Portainer? I'm still stuck trying to find a console option on the node-red image (as per the above). Sorry to bother...

**Comment by sztof** [comment]
Sorry, I have totally forgot about you. 
On my portainer i can see list of the addons
![obraz](https://user-images.githubusercontent.com/37777963/106814575-e76e4300-6672-11eb-8dc3-dc06fd124d6e.png)
![obraz](https://user-images.githubusercontent.com/37777963/106814682-0bca1f80-6673-11eb-8216-a6c041be4108.png)

if you see "Home Assitant" welcome screen then probably you are on the wrong machine.
I am using home assistant supervised, but my docker is not installed as addon, but outside of HA, I didnt know it makes a difference.
I think there may be another solution - you could try to install missing packages by executing linux command from node-red.
I havent really tried it, but worth a try.

**Comment by sztof** [comment]
@baldfox could you show me screenshot of the node-red addon from portainer?

**Comment by baldfox** [comment]
![image](https://user-images.githubusercontent.com/32448665/107479904-f3439300-6ba5-11eb-8604-8a50201eae29.png)

This is all I have, the rest is a long list of unused images.

**Comment by baldfox** [comment]
@sztof I tried the commands you listed, but build-essential wasn't available to me, i listed the methods in the other thread. I didn't want to really span both, but as this one was closed, thought wiser to continue on the open thread. It's a shame I can't get this running, I would be putting a blog post up as loads of people in the forums looking for signal messenger in HA/NR.
